### PR TITLE
2 minimizing bug cr

### PR DESCRIPTION
**Pull request by cruiter1**
This fixes the Minimizing Bug that was happening with Memoranda. The App frame now behaves like normal windows and minimizes to the dock not the system tray.

jUnit tests for Window State change correctly.

Not sure how to test for closing behavior

### CODE REVIEW

**Comment by ghost** [comment]
This works on my machine, but there are still options in the Preferences window that would change the behavior. If we're going to make this no-longer-configurable, can we remove those items from the GUI configuration>

**Comment by cruiter1** [comment]
Going to remove options from preference pane and submit new PR.

**Comment by ghost** [comment]
For future reference, any subsequent commits that you push to your branch
will update the PR.

Adam Perry

**Comment by cruiter1** [comment]
Thanks for the note Adam, I'll keep that in mind for next time.

I have adjusted the preferences panel and also fixed some other issues with it. The look and feel section didn't add labels to the Java and System features.

**Comment by cruiter1** [comment]
The radio buttons under general for look and feel dont operate together. This behavior was present before i began working on it.

**Pull request merged**
